### PR TITLE
Align apartapps and refresh app data button center

### PR DESCRIPTION
**Pull request by jaeminlee0515**
#1140

### CODE REVIEW

**Comment by silasw2** [comment]
Should probably merge develop again before requesting a review, I can take a look after develop is in!

**Comment by jaeminlee0515** [comment]
> Should probably merge develop again before requesting a review, I can take a look after develop is in!

Will do! Thanks!

**Review by silasw2 — APPROVED** [review]
LGTM! I cannot run locally so I can't see the exact changes but as long as it looks good on your end there should not be any issues.

**Comment by andrew-wzj** [comment]
> LGTM! I cannot run locally so I can't see the exact changes but as long as it looks good on your end there should not be any issues.

Awesome!

**Comment by jaeminlee0515** [comment]
> LGTM! I cannot run locally so I can't see the exact changes but as long as it looks good on your end there should not be any issues.

This is what it looked like before the fix:
image

This is what it looks like after the fix:
image

**Pull request merged**
