### PR TITLE
Release 07/10/2023

### PR DESCRIPTION
**Pull request by Centerville1**
This PR merges the following changes into production:

- #1944 
- #1844 
- #1870 
- #1850 
- #1962 
- #1966 
- #1830 
- #1917 
- #1942 
- #1824 
- #1805 
- #1951 
- #1982 
and 
- #1885

### CODE REVIEW

**Review by EjPlatzer — DISMISSED** [review]
Please see my comments on #1828, this is not ready for release yet.

**Comment by Centerville1** [comment]
> Please see my comments on #1828, this is not ready for release yet.

Those changes have been reverted by @russtuck , so we should be all set.

**Comment by russtuck** [comment]
I think Evan meant #1885, and the issue is keeping .css files out of the repo (since they are generated from .scss).  I mention this just for clarity, because the only conversation in #1828 is about how to use the new logo, and that has since been resolved in conversations with the Stephen Dagley.

**Comment by russtuck** [comment]
#2006 adds these changes:
* #1935 
* #1986
* #1998 
* #2000
* #2001 
* #2003

**Review by russtuck — DISMISSED** [review]

**Review by russtuck — APPROVED** [review]

**Pull request merged**
