### PR TITLE
S21 nickname people search

### PR DESCRIPTION
**Pull request by Kevin-Chu58**
This PR must be merged together with https://github.com/gordon-cs/gordon-360-api/pull/584 to make the whole feature works properly.

Feature added:

- If a person's nickname != firstname && nickname != firstname in the AD_Username, the found person will be shown in this format:

    **firstname lastname (nickname)**
    and the nickname will be highlighted.

 Example shown as following:
          
image

### CODE REVIEW

**Comment by Kevin-Chu58** [comment]
It seems I removed the commit on Emergency Contact Information on PersonalInfoList I made last week, but it's okay because I made a new folder on the UI for the Emergency Contact Information.

**Comment by iamphg97** [comment]
I know this is already closed. However, in my personal opinion, I think this name format is better.

Now:
First Name + Last Name + (Nick Name).

Suggestion:

First Name + (Nick Name) + Last Name

**Comment by iamphg97** [comment]
@Kevin-Chu58

**Comment by Kevin-Chu58** [comment]
@iamphg97 About the format, I checked the profile page and it uses firstname + lastname + (nickname)

**Comment by iamphg97** [comment]
I see :)

**Pull request merged**
