### PR TITLE
Rec-IM Release Branch

### PR DESCRIPTION
**Pull request by amos-cha**
(don't need to comment) I'm going to handle merge requests from the other branch's PR

### CODE REVIEW

**Comment by bennettforkner** [comment]
What is this branch for? Did you mean to use `master` as the base? Otherwise, what is the purpose?

**Comment by amos-cha** [comment]
> What is this branch for? Did you mean to use `master` as the base? Otherwise, what is the purpose?

A few kids are working on the `recim` branch and I don't want to have constant changes while I fix things and have you guys re-review this before its merge into develop. Granted, this should have been done months back.

**Comment by bennettforkner** [comment]
> A few kids are working on the `recim` branch and I don't want to have constant changes while I fix things and have you guys re-review this before its merge into develop. Granted, this should have been done months back.

Lol "kids".

Cool, thanks. I assume you are tracking any open requests on the old PR from Evan and myself?

**Comment by amos-cha** [comment]
> > A few kids are working on the `recim` branch and I don't want to have constant changes while I fix things and have you guys re-review this before its merge into develop. Granted, this should have been done months back.
> 
> Lol "kids".
> 
> Cool, thanks. I assume you are tracking any open requests on the old PR from Evan and myself?

Yeah, I've been onboarding so not much time to actually tackle them. BUT I will be doing them asap. Then we can merge this PR into `develop` and hold the `recim` branch as the develop branch

**Pull request closed without merging**
