### PR TITLE
Remove period from "By students for students" tagline

### PR DESCRIPTION
**Pull request by jsenning**
The Gordon 360 loading page contains the tag line "By students for students" at the bottom of the page.  This is actually an image file since it uses one of the College's selected fonts that is not available in the browser.  Currently the tagline ends with a period ("By students for students.") but stylistically we don't really want this.  This PR replaces the image file with one that does not have the period.

## Current loader screen:
by_students_for_students_CURRENT

## Proposed loader screen:
by_students_for_students_PROPOSED

### CODE REVIEW

**Review by EjPlatzer — APPROVED** [review]
LGTM!

**Review by Luke-W-Hart — APPROVED** [review]
LGTM^2!

**Comment by Dopey12** [comment]
LGTM^3!

**Review by Dopey12 — COMMENTED** [review]
LGTM!

**Review by Dopey12 — APPROVED** [review]
LGTM!

**Pull request merged**
