### PR TITLE
Apartapp cleanup

### PR DESCRIPTION
**Pull request by NerdyGriffin**
This branch includes minor UI styling improvements and better readability/conciseness of the code in general (or at least that was my goal)

One of the other key improvements of this branch comes from the fact that I learned about `service/error.js` and learned how to properly check the error types of the error codes received from the API.

### CODE REVIEW

**Review by joshuaRogers24 — CHANGES_REQUESTED** [review]
Ah, it's nice to see less errors in the console! The save button icon is great, too! However, you are now able to add people who are on existing applications. I will send pictures in Slack.

**Comment by NerdyGriffin** [comment]
> Ah, it's nice to see less errors in the console! The save button icon is great, too! However, you are now able to add people who are on existing applications. I will send pictures in Slack.

This issue should now be fixed

**Review by joshuaRogers24 — APPROVED** [review]
Thank God! Nice Work! I did find a small issue where attempting to change the editor of a submitted application with unsaved changes failed, but you can change the editor after submission as long as you save changes first.

**Comment by NerdyGriffin** [comment]
> Thank God! Nice Work! I did find a small issue where attempting to change the editor of a submitted application with unsaved changes failed, but you can change the editor after submission as long as you save changes first.

Okay, I will explore that in a new branch 😆

**Comment by NerdyGriffin** [comment]
> Thank God! Nice Work! I did find a small issue where attempting to change the editor of a submitted application with unsaved changes failed, but you can change the editor after submission as long as you save changes first.

That is strange, because the "change editor" automatically saves the whole application at the same time

**Pull request merged**
