### PR TITLE
Hl prefer box

### PR DESCRIPTION
**Pull request by andrew-wzj**
Preference survey for the housing lottery.

### CODE REVIEW

**Review by andrew-wzj — COMMENTED** [review]
change the .env.development and .env.production for causing conflicting url

**Review by andrew-wzj — COMMENTED** [review]
Now the build issue should be solved

**Review by andrew-wzj — COMMENTED** [review]
Remove empty comments!

**Review by russtuck — COMMENTED** [review]
Even though this is merged, I hope you'll take a look at my questions and comments.

**Pull request merged**
