### PR TITLE
Header and Navigation Overhaul

### PR DESCRIPTION
**Pull request by Centerville1**
To prepare for a future feature of allowing users to pick their favorite tabs to put on the header, and to make room for the Recim tab, we've made a number of modifications to the header and navigation methods on the site.

Changes:

- Removed Home tab from the header
- Made the left side hamburger menu visible on all devices, will become the primary navigation menu on all devices (improved consistency between desktop and mobile)
- Removed the right side navigation menu, replaced by hamburger menu
- Made the right side nav avatar a direct link to the myProfile page, and made it move to the left side menu on smaller screens

New Header on regular 360:
Screenshot from 2023-07-20 11-25-05

Left side nav drawer on large screens:
Screenshot from 2023-07-20 15-37-27

Left side nav drawer on small screens:
Screenshot from 2023-07-20 15-37-36

### CODE REVIEW

**Review by russtuck — DISMISSED** [review]
I wish I had time to read this all more carefully, but it looks good and logical, and works correctly in my testing.

**Review by jsenning — CHANGES_REQUESTED** [review]
I suggest adding another 
          ```<Typography className={`disable_select ${styles.title}`} variant="h6" color="inherit">
            {/* This h6 box uses flex to keep people search and the profile button stuck to the right side of the header */}
          </Typography>```
between the div for the navigation icons and the people search box.  This will balance the header a bit better on a wide screen.

**Review by jsenning — APPROVED** [review]
LGTM

**Review by EjPlatzer — APPROVED** [review]
LGTM! I like these changes a lot!

I am working on an update on top of this that simplifies the CSS and html a fair bit, but we should definitely merge this first.

**Comment by Centerville1** [comment]
> LGTM! I like these changes a lot!
> 
> I am working on an update on top of this that simplifies the CSS and html a fair bit, but we should definitely merge this first.

That would be great, the logic and styling of the header is definitely overcomplicated currently!

**Pull request merged**
