### PR TITLE
People search

### PR DESCRIPTION
**Pull request by TheGreatMaximus**
people search suggestions now lines up with search bar 
Added bottom padding to search suggestions

### CODE REVIEW

**Comment by TheGreatMaximus** [comment]
looks like there is a problem where there is a vertical scroll bar if the list gets too big

**Comment by TheGreatMaximus** [comment]
screenshot from 2018-07-16 11-21-40

**Comment by TheGreatMaximus** [comment]
screenshot from 2018-07-16 11-23-08

**Comment by TheGreatMaximus** [comment]
screenshot from 2018-07-16 12-35-58

**Comment by TheGreatMaximus** [comment]
screenshot from 2018-07-16 12-36-21

**Comment by softwary** [comment]
LGTM

**Pull request merged**
