### PR TITLE
changed all 'componentWillMount' to 'componentDidMount

### PR DESCRIPTION
**Pull request by dezy-x2**
This new branch should be able to fix issue #962 by swapping every instance of `componentWillMount()` to `componentDidMount()`

### CODE REVIEW

**Comment by EjPlatzer** [comment]
Thank you for your contribution, this is quite helpful!

It looks you might have missed two instances of `componentWillMount` though, specifically in `src\views\ActivityProfile\components\GroupContacts\index.js` and `src\views\ActivityProfile\components\Advisors\index.js`.

Once you remove those, we will begin testing this to verify that all components still work as intended. If we can test and verify it, we'll be happy to merge it in.

**Comment by dezy-x2** [comment]
With this latest commit all instances of `componentWillMount()` should be gone, if there's anything else please let me know!

**Comment by EjPlatzer** [comment]
These changes are excellent and we would like to merge them, but not into our default `develop` branch. I've created the branch `removeWillMount`. If you make a new pull request to merge there, I will review and merge it.

**Comment by EjPlatzer** [comment]
This is resolved by #966.

**Pull request closed without merging**
