### PR TITLE
Fix Involvement Member Links on small screens

### LINKED ISSUE #1638: Involvement Profile: link to member profiles broken on small screens
On the Involvement Profile page, the link to users' profiles is broken on small screens.

The issue is in `/src/views/InvolvementProfile/components/Membership/components/MemberList/components/MemberListItem/index.jsx`. It appears that the large screen view links to `/profile/${member.Username}`, whereas the small screen view links to `/profile/${member.AD_Username}`. 

When we refactored Memberships, I think the member item was changed and the `AD_Username` property is now `Username`, but the links weren't changed everywhere.

### PR DESCRIPTION
**Pull request by charlielee144r**
This PR fixes the member profile links in an involvement on small screens by fixing a variable name.

Fixes #1638

### CODE REVIEW

**Comment by charlielee144r** [comment]
One thing I noticed - this might be a whole new issue - was that in admin view for an involvement, the links to some of the profiles are not active. Not sure if this is an official bug or not, but the profile links in the 'Group Contacts' are active.
image

**Comment by Kevin-Chu58** [comment]
> One thing I noticed - this might be a whole new issue - was that in admin view for an involvement, the links to some of the profiles are not active. Not sure if this is an official bug or not, but the profile links in the 'Group Contacts' are active. image

That might be caused by one of my prs that, for student accounts they can see alumni in the involvement profile page, but they are not authorized to access their profiles. So I removed the links to alumni profiles if the current user is a student. You may want to check out the logic again.

**Comment by charlielee144r** [comment]
> > One thing I noticed - this might be a whole new issue - was that in admin view for an involvement, the links to some of the profiles are not active. Not sure if this is an official bug or not, but the profile links in the 'Group Contacts' are active. image
> 
> That might be caused by one of my prs that, for student accounts they can see alumni in the involvement profile page, but they are not authorized to access their profiles. So I removed the links to alumni profiles if the current user is a student. You may want to check out the logic again.

Alright, I'll check it out! Thanks for the heads up.

**Review by bennettforkner — APPROVED** [review]
LGTM!
This is a great fix. It would also be good to fix the issue that you mention in your previous comments, but that can be done in a consecutive PR if you would like. Up to you.

**Comment by charlielee144r** [comment]
> > One thing I noticed - this might be a whole new issue - was that in admin view for an involvement, the links to some of the profiles are not active. Not sure if this is an official bug or not, but the profile links in the 'Group Contacts' are active. image
> 
> That might be caused by one of my prs that, for student accounts they can see alumni in the involvement profile page, but they are not authorized to access their profiles. So I removed the links to alumni profiles if the current user is a student. You may want to check out the logic again.

Dealt with in issue #1748

**Pull request merged**
